---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:1.15
    environment:
      GOPROXY: https://athens.chuhlomin.com
      CGO_ENABLED: "0"
      GOOS: linux
      GOARCH: amd64
    commands:
      - go test ./...
      - cd cmd/server
      - >
        go build -mod=readonly -a -installsuffix cgo \
          -ldflags="-w -s -X main.revision=$DRONE_BRANCH-${DRONE_COMMIT:0:7}-$(date +%Y%m%d-%H:%M:%S)" \
          -o server main.go
    when:
      event:
        - push
      branch:
        - main

  - name: cr
    image: plugins/docker
    settings:
      registry: cr.chuhlomin.com
      repo: cr.chuhlomin.com/gbfs-graphql
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      context: ./cmd/server
      dockerfile: cmd/server/Dockerfile
      tags:
        - ${DRONE_COMMIT}
        - latest
    when:
      event:
        - push
      branch:
        - main

  - name: deploy
    image: cr.chuhlomin.com/docker-run:0.8
    settings:
      server: delta.chuhlomin.com
      username: drone
      sudo: true
      docker_image: cr.chuhlomin.com/gbfs-graphql:${DRONE_COMMIT}
      docker_network: delta_default
      docker_network_alias: gbfs-graphql
      labels:
        caddy: gbfs.chuhlomin.com
        caddy.reverse_proxy: gbfs-graphql:8080
        prometheus.scrape: true
        prometheus.port: 6000
      envs:
        HOST: "0.0.0.0"
        PORT: "8080"
        DB_PATH: "/data/bolt.db"
        CORS_ALLOW_ORIGIN: "bike.chuhlomin.com"
      mounts:
        - /etc/gbfs/:/data/:Z
    environment:
      SSH_KEY:
        from_secret: ssh_key
    when:
      event:
        - push
      branch:
        - main

trigger:
  event:
    - push

image_pull_secrets:
  - dockerconfigjson
