FROM --platform=$BUILDPLATFORM golang:1.22 AS builder
WORKDIR /app/
COPY . .
RUN go test ./...

ARG TARGETOS
ARG TARGETARCH

RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -ldflags="-w -s" -mod=vendor -buildvcs \
    -a -installsuffix cgo \
    -o server cmd/server/main.go


FROM gcr.io/distroless/static:latest
COPY --from=builder /app/server /server
CMD ["/server"]
