---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .app }}
  labels:
    app: {{ .app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .app }}
  template:
    metadata:
      labels:
        app: {{ .app }}
    spec:
      volumes:
        - name: db
          emptyDir: {}
      containers:
        - name: gbfs-graphql
          image: {{ .image }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 50m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 200Mi
          volumeMounts:
            - name: db
              mountPath: /db
          env:
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: PORT
              value: "8080"
            - name: REDIS_ADDR
              value: redis:6379
            - name: CORS_ALLOW_ORIGIN
              value: "{{ .cors_allow_origin }}"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .app }}
spec:
  type: ClusterIP
  selector:
    app: {{ .app }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .app }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: {{ .domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .app }}
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .domain }}
      secretName: {{ .app }}-ingress-cert
