---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .app }}
  labels:
    app: {{ .app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .app }}
  template:
    metadata:
      labels:
        app: {{ .app }}
    spec:
      containers:
        - name: busnj-console
          image: {{ .image }}
          ports:
            - containerPort: 80
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "80"
            - name: CORS_ALLOW_ORIGIN
              value: "{{ .cors_allow_origin }}"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .app }}
spec:
  type: ClusterIP
  selector:
    app: {{ .app }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .app }}
spec:
  domains:
    - {{ .domain }}
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ssl-redirect-{{ .app }}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .app }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .app }}
    networking.gke.io/managed-certificates: {{ .app }}
    ingress.kubernetes.io/force-ssl-redirect: "true"
    networking.gke.io/v1beta1.FrontendConfig: ssl-redirect-{{ .app }}
spec:
  backend:
    serviceName: {{ .app }}
    servicePort: 80
