version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.15
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            cd cmd/server
            CGO_ENABLED=0 GOOS=linux go build -mod=readonly -a -installsuffix cgo -o server -ldflags \
              "-X main.revision=$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}-$(date +%Y%m%d-%H:%M:%S)" main.go
      - persist_to_workspace:
          root: .
          paths:
            - .
  cr:
    docker:
      - image: docker:20.10.1-git
    working_directory: ~/project
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD cr.chuhlomin.com
      - run:
          command: |
            cd ~/project/cmd/server
            docker build -t cr.chuhlomin.com/gbfs-graphql:circleci-${CIRCLE_SHA1} .
      - run: docker push cr.chuhlomin.com/gbfs-graphql:circleci-${CIRCLE_SHA1}

workflows:
  build_and_cr:
    jobs:
      - build
      - cr:
          requires:
            - build
