name: main

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: ghcr.io/chuhlomin/gbfs-graphql

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.15'

      - run: go test ./...

      - name: Build and push to CR
        uses: chuhlomin/actions/docker-build-push@main
        with:
          dockerfile: Dockerfile.server
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PKG_TOKEN }}
          image_name: ${{ env.DOCKER_IMAGE }}
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          platforms: linux/arm64

      - name: Deploy
        uses: chuhlomin/actions/deploy@main
        with:
          server: dev1.chuhlomin.com
          service: gbfs/graphql
          tag: ${{ github.sha }}
          auth: ${{ secrets.DEPLOY_AUTH }}
