name: main

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: ghcr.io/chuhlomin/gbfs-graphql

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'

      - run: go test ./...
      - name: Build server binary
        env:
          CGO_ENABLED: "0"
          GOOS: linux
          GOARCH: amd64
        working-directory: ./cmd/server
        run: |
          go build -mod=readonly -a -installsuffix cgo \
            -ldflags="-w -s -X main.revision=${GITHUB_REF#refs/heads/}-${{ github.sha }}-$(date +%Y%m%d-%H:%M:%S)" \
            -o server main.go

      - name: Build and push to CR
        uses: chuhlomin/actions/docker-build-push@main
        with:
          dockerfile: Dockerfile.server
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PKG_TOKEN }}
          image_name: ${{ env.DOCKER_IMAGE }}
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Deploy to GKE
        uses: chuhlomin/actions/deploy-gke@main
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          cluster_name: cluster-east
          location: us-east4-c
          vars: |
            app: gbfs-graphql
            image: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            domain: gbfs.chuhlomin.com
            cors_allow_origin: https://bike.chuhlomin.com
          rollout_status_wait: deployment/gbfs-graphql
